languag:Android
sudo: required
jdk:
  - oraclejdk8

  env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.0
android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - tools
    - tools
    - platform-tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - build-tools-28.0.0
    - android-28
    - sys-img-armeabi-v7a-android-22


 before_install:
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
- nvm install 8
- node --version
- npm --version
- npm install -g $appiumVersion
- yes | sdkmanager "platforms;android-27"
- yes | sdkmanager "platforms;android-28"
before_script:

    # Create emulator (emulator image version should be exist in previous android setting)
    - echo no | android create avd --force -n test -t android-28 --abi armeabi-v7a

    # Run emulator
    - emulator -avd test -no-skin -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script: "mvn test"

cache:
    directories:
    - $HOME/.m2

notifications:
    email:
        - sheetansh@simforsolutions.com
