language: android
sudo: required
jdk: oraclejdk8

android:
    components:
        - tools
        - platform-tools
        - build-tools-25.0.1
        - android-25
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
        - addon-google_apis-google-25
        - sys-img-armeabi-v7a-android-25


before_install:
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
- nvm install 8
- node --version
- npm --version
- npm install -g appium
- yes | sdkmanager "platforms;android-25"
before_script:

    # Create emulator (emulator image version should be exist in previous android setting)
    - echo no | android create avd --force --name test --target android-25 --armeabi-v7a
    # Run emulator
    #- echo no | android create avd --force --device "Nexus 5" --name test --target android-22 --abi armeabi-v7a --skin WVGA800 --sdcard 512M
    - emulator -avd test -no-skin -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script: "mvn test"

cache:
    directories:
    - $HOME/.m2

notifications:
    email:
        - sheetansh@simforsolutions.com
